### ISSUE TITLE
추억 - 태담+음악 생성 시 캐릭터 음성 변환 (TTS)

### ISSUE THREAD

**Issue by korogoo** [KUIT-AGARANG/Agarang-Backend#7]
## 어떤 기능인가요?

> 추가하려는 기능에 대해 간결하게 설명해주세요

<img src="https://github.com/KUIT-AGARANG/Agarang-Backend/assets/126454114/65a16d9d-a428-4461-a074-4250a33114b6" width="200" height="400"/>

### ✨수정✨
<img src="https://github.com/KUIT-AGARANG/Agarang-Backend/assets/126454114/a405f0d9-9c6b-4820-bdfb-c3e058c97f3e" height="400"/>

위 캐릭터가 사용자에게 질문하는 텍스트를 음성 파일로 변환하여 다운로드 URL 을 반환합니다. (응답형태 미정)
이때 텍스트는 gpt api 를 통해 자동생성된 문자열입니다.

<br/>

## 작업 상세 내용

- [x] WebClient 반영하기
- [x] 음성파일 반환 요청, 응답 테스트 및 서비스 구현

<br/>

## 참고할만한 자료(선택)

[Typecast API Docs](https://docs.typecast.ai/index.html)

**Comment by rlagkswn00** [comment]
PM님한테 확인했는데 이 부분은 TTS로 제공하는건 아니고, GPT를 통해서 홈 화면 조회시마다 새롭게 생성하는걸로 전달 받았습니다.
캐릭터 말풍선 내용을 TTS 전달하는 기능 내용이 어디에 있는지 못찾았는데, 혹시 노션이나 피그마에 있다면 태그 부탁드려요!

**Comment by korogoo** [comment]
다시 확인해보니 홈화면 말풍선 내용이 아니라 추억카드 생성 시 캐릭터의 질문을 TTS 로 변환하는 거군요!
피그마는 잘 작성되어있는데 제가 착각했습니다..ㅎㅎ
기능 상 다른 곳에 가져다 써도 문제없어서 uri 만 수정하겠습니다!
